#
#spring:
#    profiles:
#        active: native
#spring:
#    cloud:
#        config:
#            server:
#                git:
#                    uri: https://github.com/phamvanoanh/microservices-netflix
#                    search-paths:
#                        - "ms-config-properties/{application}/{profile}"
spring:
    profiles:
        active: native
---
spring:
    profiles: native
    cloud:
        config:
            server:
                native:
                    search-locations:
                        file://PATH_TO_MICROSERVICES_PROJECT/ms-config-properties/{application}/{profile},
                        file://PATH_TO_MICROSERVICES_PROJECT/ms-config-properties/global/{profile}
---
spring:
    profiles: git
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/phamvanoanh/microservices-netflix
                    search-paths:
                        - "ms-config-properties/{application}/{profile}"
                        - "ms-config-properties/global/{profile}"