spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/phamvanoanh/microservices-netflix
                    search-paths:
                        - "ms-config-properties/{application}/{profile}"